#!/bin/bash
# thanks to xxx for pxsup2dast.c 
#	 to AnMaster for general help and examples with bash scripting
# 	 to Rick Harris for the any2dvd script
#	 to the people who made projectx, tcmplex and dvdauthor
#
# You may contact the author at mikael.lammentausta(at)student.savonia-amk.fi
#			or memo ruxpin@freenode


VERSION=20060817


### TODO ##############
# usage: -i tai ei mit‰‰n: toiminta sama
# -o voi ottaa hakemiston, tiedostonimen tai molemmat
# if WORKDIR etc is not defined by cli or here, default to $BASEDIR
# if -o defines directory, use that as WORKDIR
# -v | --verbose 	= verbose
# --subdelay 		= delay (in ms) for subtitles (pass to pxsup2dast)
# tcmplex: *** -alkuiset > stdout ; INFO > stderr
# jos inputin p‰‰tett‰ ei m‰‰ritell‰, pit‰isi silti siirt‰‰/poistaa!
# dvdxmlauth: vain pelkk‰ create menus mahdollisuus!


### SOURCE FUNCTIONS and PATHS ##########
source "$(type -p ts2vob.functions)"
source "$(type -p bash.functions)"
source /etc/dvb2vob.conf
source /usr/bin/gettext.sh



PRINT_ts2vob_Info


### PARSING THE ARGUMENTS ###########

ParseArgs "$@"


### CHECKING DEPENDENCIES ###########

CheckDeps;  

if [ "$DEPFAIL" -eq "1" ]; then 
	echo -n ${tcRED}
	eval_gettext $"CRITICAL DEPENDENCIES ARE MISSING, EMERGE ;-)"
	echo ${tSTD};
	exit 0;
fi



### DEBUG ###

echo -ne "  [${tcGREEN}OK${tSTD}]\t" && \
eval_gettext $"Input file: " ; echo ${INPUT}


### CHECK IF USER HAS DEMUXED SOURCE ALREADY  #######
demux


### MULTIPLEX TO VOB #######
multiplex


#### PROCESS SUBTITLES, if they exist... ##########
process_Subtitles 

### CLEAN ######
clean
